### PR TITLE
Added support for default gravatar image, Changed React.proptypes to prop-types.

### PR DESCRIPTION
**Pull request by SPATAN18**
### I encountered the following issues while using this great module:

- Unable to handle empty or invalid email prop.
- Issues in gravatar resizing.

### I have made following updates:

-  added default parameter in the gravatar uri, now it can handle the invalid or null email address.
-  added **resizeMode** prop to gravatar with default to **contain**.
-  replaced React.proptypes with prop-types.
-  updated readme.md file with a table of available proptypes.

I am open for discussion about changes.
Thanks again, for creating such an awesome library.

### CODE REVIEW

**Review by niborb — COMMENTED** [review]
Thanks for this PR. I will try to review it tomorrow.

**Comment by SPATAN18** [comment]
@niborb, I am waiting for your review. 
If, there is some issue that you want to get resolved then please, inform me so that I can work on that.

**Comment by niborb** [comment]
thanks! 👍

**Comment by SPATAN18** [comment]
@niborb, it's my honour to be able to contribute something.

**Pull request merged**
